target: AnywordDataset
params:

  data_root: '../benchmark/ic13'
  json_name: 'test.json'

  H: 512
  W: 512
  word_len: [1, 12]
  seq_len: 12
  mask_min_ratio: 0
  aug_text_enabled: False
  aug_text_ratio: 1.0